//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.28 at 12:28:33 PM SAMT 
//


package com.converter.shop;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SimpleShop }
     * 
     */
    public SimpleShop createSimpleShop() {
        return new SimpleShop();
    }

    /**
     * Create an instance of {@link SimpleShop.Categories }
     * 
     */
    public SimpleShop.Categories createSimpleShopCategories() {
        return new SimpleShop.Categories();
    }

    /**
     * Create an instance of {@link SimpleShop.Categories.Subcategories }
     * 
     */
    public SimpleShop.Categories.Subcategories createSimpleShopCategoriesSubcategories() {
        return new SimpleShop.Categories.Subcategories();
    }

    /**
     * Create an instance of {@link SimpleShop.Categories.Subcategories.Products }
     * 
     */
    public SimpleShop.Categories.Subcategories.Products createSimpleShopCategoriesSubcategoriesProducts() {
        return new SimpleShop.Categories.Subcategories.Products();
    }

}
