//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.28 at 12:28:33 PM SAMT 
//


package com.converter.shop;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="categories" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="subcategories" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="products">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="maker" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="isInStock" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                       &lt;element name="color">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;enumeration value="RED"/>
 *                                             &lt;enumeration value="BLACK"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="test" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "categories"
})
@XmlRootElement(name = "simpleShop")
public class SimpleShop {

    @XmlElement(required = true)
    protected List<SimpleShop.Categories> categories;

    /**
     * Gets the value of the categories property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categories property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategories().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleShop.Categories }
     * 
     * 
     */
    public List<SimpleShop.Categories> getCategories() {
        if (categories == null) {
            categories = new ArrayList<SimpleShop.Categories>();
        }
        return this.categories;
    }

    @Override
    public String toString() {
        return "SimpleShop{" +
                "categories=" + categories +
                '}';
    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="subcategories" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="products">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="maker" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                             &lt;element name="isInStock" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                             &lt;element name="color">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;enumeration value="RED"/>
     *                                   &lt;enumeration value="BLACK"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="test" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "subcategories"
    })
    public static class Categories {
        @Override
        public String toString() {
            return "Categories{" +
                    "name='" + name + '\'' +
                    ", subcategories=" + subcategories +
                    '}';
        }

        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected List<SimpleShop.Categories.Subcategories> subcategories;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the subcategories property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the subcategories property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSubcategories().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SimpleShop.Categories.Subcategories }
         * 
         * 
         */
        public List<SimpleShop.Categories.Subcategories> getSubcategories() {
            if (subcategories == null) {
                subcategories = new ArrayList<SimpleShop.Categories.Subcategories>();
            }
            return this.subcategories;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="products">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="maker" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *                   &lt;element name="isInStock" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                   &lt;element name="color">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;enumeration value="RED"/>
         *                         &lt;enumeration value="BLACK"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="test" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "products"
        })
        public static class Subcategories {
            @Override
            public String toString() {
                return "Subcategories{" +
                        "name='" + name + '\'' +
                        ", products=" + products +
                        '}';
            }

            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected SimpleShop.Categories.Subcategories.Products products;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the products property.
             * 
             * @return
             *     possible object is
             *     {@link SimpleShop.Categories.Subcategories.Products }
             *     
             */
            public SimpleShop.Categories.Subcategories.Products getProducts() {
                return products;
            }

            /**
             * Sets the value of the products property.
             * 
             * @param value
             *     allowed object is
             *     {@link SimpleShop.Categories.Subcategories.Products }
             *     
             */
            public void setProducts(SimpleShop.Categories.Subcategories.Products value) {
                this.products = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="maker" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}double"/>
             *         &lt;element name="isInStock" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *         &lt;element name="color">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;enumeration value="RED"/>
             *               &lt;enumeration value="BLACK"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="test" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "maker",
                "model",
                "creationDate",
                "price",
                "isInStock",
                "color"
            })
            public static class Products {

                @XmlElement(required = true)
                protected String maker;
                @XmlElement(required = true)
                protected String model;
                @XmlElement(required = true)
                protected String creationDate;
                protected double price;
                protected boolean isInStock;
                @XmlElement(required = true)
                protected String color;
                @XmlAttribute(name = "test")
                protected String test;

                /**
                 * Gets the value of the maker property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMaker() {
                    return maker;
                }

                /**
                 * Sets the value of the maker property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMaker(String value) {
                    this.maker = value;
                }

                /**
                 * Gets the value of the model property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getModel() {
                    return model;
                }

                /**
                 * Sets the value of the model property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setModel(String value) {
                    this.model = value;
                }

                /**
                 * Gets the value of the creationDate property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCreationDate() {
                    return creationDate;
                }

                /**
                 * Sets the value of the creationDate property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCreationDate(String value) {
                    this.creationDate = value;
                }

                /**
                 * Gets the value of the price property.
                 * 
                 */
                public double getPrice() {
                    return price;
                }

                /**
                 * Sets the value of the price property.
                 * 
                 */
                public void setPrice(double value) {
                    this.price = value;
                }

                /**
                 * Gets the value of the isInStock property.
                 * 
                 */
                public boolean isIsInStock() {
                    return isInStock;
                }

                /**
                 * Sets the value of the isInStock property.
                 * 
                 */
                public void setIsInStock(boolean value) {
                    this.isInStock = value;
                }

                /**
                 * Gets the value of the color property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getColor() {
                    return color;
                }

                /**
                 * Sets the value of the color property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setColor(String value) {
                    this.color = value;
                }

                /**
                 * Gets the value of the test property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTest() {
                    return test;
                }

                /**
                 * Sets the value of the test property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTest(String value) {
                    this.test = value;
                }

            }

        }

    }

}
